In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("Data/wiki_data.csv", sep=';')
df

,url,text
0,https://en.wikipedia.org/wiki/Adolf_Hitler,Adolf Hitler (German: ['ad?lf 'h?tl?] (listen)...
1,https://en.wikipedia.org/wiki/illegitimate,"Legitimacy, in traditional Western common law,..."
2,https://en.wikipedia.org/wiki/nazi_salute,"The Nazi salute, Hitler salute (German: Hitler..."
3,https://en.wikipedia.org/wiki/czech_language,"Czech (/t??k/; Czech ceština ['t???c?na]), his..."
4,https://en.wikipedia.org/wiki/minnesota,Minnesota (/?m?n?'so?t?/ (listen)) is a state ...
...,...,...
14574,https://en.wikipedia.org/wiki/tanesco,The Tanzania Electric Supply Company Limited (...
14575,https://en.wikipedia.org/wiki/black_rhinoceros,The black rhinoceros or hook-lipped rhinoceros...
14576,https://en.wikipedia.org/wiki/coat_of_arms_of_...,The coat of arms of Tanzania comprises a warri...
14577,https://en.wikipedia.org/wiki/halotel,"Viettel Tanzania Public Limited Company, tradi..."
14578,https://en.wikipedia.org/wiki/zanzibari_ryal,The ryal (Arabic: ?????) was the currency of Z...

In [3]:
to_delete = []
for index, row in df.iterrows():
    if len(row.text) < 150:
        to_delete.append(index)

In [5]:
df = df.drop(to_delete)

KeyError: '[   53   102   117 ... 14514 14520 14521] not found in axis'

In [6]:
df

,url,text
0,https://en.wikipedia.org/wiki/Adolf_Hitler,Adolf Hitler (German: ['ad?lf 'h?tl?] (listen)...
1,https://en.wikipedia.org/wiki/illegitimate,"Legitimacy, in traditional Western common law,..."
2,https://en.wikipedia.org/wiki/nazi_salute,"The Nazi salute, Hitler salute (German: Hitler..."
3,https://en.wikipedia.org/wiki/czech_language,"Czech (/t??k/; Czech ceština ['t???c?na]), his..."
4,https://en.wikipedia.org/wiki/minnesota,Minnesota (/?m?n?'so?t?/ (listen)) is a state ...
...,...,...
14574,https://en.wikipedia.org/wiki/tanesco,The Tanzania Electric Supply Company Limited (...
14575,https://en.wikipedia.org/wiki/black_rhinoceros,The black rhinoceros or hook-lipped rhinoceros...
14576,https://en.wikipedia.org/wiki/coat_of_arms_of_...,The coat of arms of Tanzania comprises a warri...
14577,https://en.wikipedia.org/wiki/halotel,"Viettel Tanzania Public Limited Company, tradi..."
14578,https://en.wikipedia.org/wiki/zanzibari_ryal,The ryal (Arabic: ?????) was the currency of Z...

In [7]:
df.to_csv("Data/wiki_data.csv")

In [6]:
df

,url,text
0,https://en.wikipedia.org/wiki/Adolf_Hitler,Adolf Hitler (German: ['ad?lf 'h?tl?] (listen)...
1,https://en.wikipedia.org/wiki/illegitimate,"Legitimacy, in traditional Western common law,..."
2,https://en.wikipedia.org/wiki/nazi_salute,"The Nazi salute, Hitler salute (German: Hitler..."
3,https://en.wikipedia.org/wiki/czech_language,"Czech (/t??k/; Czech ceština ['t???c?na]), his..."
4,https://en.wikipedia.org/wiki/minnesota,Minnesota (/?m?n?'so?t?/ (listen)) is a state ...
...,...,...
6315,https://en.wikipedia.org/wiki/fountains_abbey,Fountains Abbey is one of the largest and best...
6317,https://en.wikipedia.org/wiki/archbishop_of_york,The Archbishop of York is a senior bishop in t...
6318,https://en.wikipedia.org/wiki/thurstan,Thurstan[a] or Turstin of Bayeux (c. 1070 – 6 ...
6320,https://en.wikipedia.org/wiki/ossian,"Ossian (/'???n, '?si?n/; Irish Gaelic/Scottish..."
6321,https://en.wikipedia.org/wiki/ealdred_(bishop),Ealdred (or Aldred;[1] died 11 September 1069)...

In [7]:
df["url"].to_csv("Data/urls_clear.csv")